name: Run PowerShell Scripts

on:
  push:
    branches:
      - PowerShell
  pull_request:
    branches:
      - PowerShell

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: pwsh -File Bot_Director.ps1
